"""empty message

Revision ID: cbd822098f03
Revises: 2a809ff65044
Create Date: 2020-07-01 21:12:08.061325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd822098f03'
down_revision = '2a809ff65044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_data_chat_id'), 'user_data', ['chat_id'], unique=True)
    op.create_index(op.f('ix_user_data_user_id'), 'user_data', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_data_username'), 'user_data', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_data_username'), table_name='user_data')
    op.drop_index(op.f('ix_user_data_user_id'), table_name='user_data')
    op.drop_index(op.f('ix_user_data_chat_id'), table_name='user_data')
    op.drop_table('user_data')
    # ### end Alembic commands ###
